# Generated by Django 4.2.30 on 2026-05-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Désignation')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('unite_mesure', models.CharField(default='unité', max_length=20, verbose_name='Unité de mesure (kilo, litre, mètre...)')),
                ('tva', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='TVA (%)')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, verbose_name="Seuil d'alerte")),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (Achat)'), ('SORTIE', 'Sortie (Vente)')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (facultatif, sinon celui du produit)')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='Nom du fournisseur')),
                ('numero_facture_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='N° facture fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('mouvement', models.OneToOneField(limit_choices_to={'type_mouvement': 'SORTIE'}, on_delete=django.db.models.deletion.CASCADE, to='stock.mouvement')),
            ],
        ),
    ]
