# Generated by Django 4.2.30 on 2026-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du fournisseur'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='numero_facture_fournisseur',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° facture fournisseur'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (facultatif, sinon celui du produit)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=0, verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='produit',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(default='unité', max_length=20, verbose_name='Unité de mesure (kilo, litre, mètre...)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client_nom',
            field=models.CharField(max_length=200, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée (Achat)'), ('SORTIE', 'Sortie (Vente)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT'),
        ),
    ]
