# Generated by Django 5.1.15 on 2026-05-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='tva',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='unite_mesure',
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=4, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('U', 'Unité(s)'), ('KG', 'Kilogramme(s)'), ('L', 'Litre(s)'), ('M', 'Mètre(s)')], default='U', max_length=2, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client_nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=5, verbose_name='Seuil d’alerte'),
        ),
    ]
