services:
  - type: web
    name: mon_stock
    env: python
    plan: free
    workingDirectory: "src"
    # Use build.sh which installs deps, runs migrations, collectstatic and creates superuser
    buildCommand: "bash build.sh"
    startCommand: "gunicorn mon_stock.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,127.0.0.1,localhost"
      - key: DATABASE_URL
        scope: run
